### ISSUE TITLE
RCWA 4.6.4 test fails in GAP stable-4.10 branch

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/rcwa#17] opened 2019-04-22 21:57 UTC
https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10/jobs/523030760 reports 1 diff when all packages are loaded:
```
########> Diff in /home/gap/inst/gap-stable-4.10/pkg/rcwa-4.6.4/tst/integral.t\
st:1103
# Input is:
phi := IsomorphismPermGroup(G);
# Expected output:
[ <rcwa permutation of Z with modulus 2, of order 2>, 
  <rcwa permutation of Z with modulus 3, of order 3> ] -> 
[ (1,6)(2,3)(4,5), (1,5,6)(2,3,4) ]
# But found:
MappingByFunction( <rcwa group over Z with 2 generators, of order 
24>, Group([ (1,3)(2,5)(4,7)(6,10)(8,12)(9,13)(11,16)(14,19)(15,20)(17,21)
(18,22)(23,24), (1,4,8)(2,6,3)(5,9,14)(7,11,17)(10,15,16)(12,18,13)(19,23,20)
(21,24,22) ]), function( x ) ... end, function( x ) ... end )
########
```
This does not happen in the GAP master branch, so you may decide to ignore this and wait till GAP 4.11.0, but for now I will move RCWA to "staging" tests for the GAP stable-4.10 branch: https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10-staging

**Comment by fingolfin** [comment] 2019-09-06 09:29
I never was able to reproduce this. But on https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10-staging/jobs/581241683 I now see this:
```
########> Diff in /home/gap/inst/gap-stable-4.10/pkg/rcwa-4.6.4/tst/integral.t\
st:1103
# Input is:
phi := IsomorphismPermGroup(G);
# Expected output:
[ <rcwa permutation of Z with modulus 2, of order 2>, 
  <rcwa permutation of Z with modulus 3, of order 3> ] -> 
[ (1,6)(2,3)(4,5), (1,5,6)(2,3,4) ]
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `RightCayleyDigraph' on 1 arguments
########
```

And on https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-devel/jobs/581480789 it just hangs -- because it tries to enumerate an infinite group. But that should be fixed by the second commit in https://github.com/gap-system/gap/pull/3646 (which "fixes" `IsomorphismFpGroup` for C_3).

**Closed as completed** 2019-09-06 09:50 UTC
