### ISSUE TITLE
Failing tests when all packages loaded in the GAP master branch

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/rcwa#21] opened 2019-10-19 19:52 UTC
Please see https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-staging/jobs/600105776
```
########> Diff in /home/gap/inst/gap-master/pkg/rcwa-4.6.4/tst/integral.tst:
1103
# Input is:
phi := IsomorphismPermGroup(G);
# Expected output:
[ <rcwa permutation of Z with modulus 2, of order 2>, 
  <rcwa permutation of Z with modulus 3, of order 3> ] -> 
[ (1,6)(2,3)(4,5), (1,5,6)(2,3,4) ]
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `RightCayleyDigraph' on 1 arguments
########
```
and then 5 more diffs likely caused by this.

**Comment by Stefan-Kohl** [comment] 2019-10-22 11:00
This seems to be triggered by changes outside RCWA. -- Is there anything I could do about this?

**Comment by olexandr-konovalov** [comment] 2019-10-22 11:03
@Stefan-Kohl thanks - if you can help and investigate what triggered this, that may be helpful.

**Comment by Stefan-Kohl** [comment] 2019-10-22 16:49
@alex-konovalov Possibly I could guess something if I would see the full backtrace -- but without, I fear this would require reproducing your precise test settings.

**Comment by olexandr-konovalov** [comment] 2019-10-22 16:54
In the master branch of GAP, with packages from https://www.gap-system.org/pub/gap/gap4pkgs/packages-master.tar.gz :
```
gap> g2 := RcwaMapping((1,2,3),[1..3]);
<rcwa permutation of Z with modulus 3, of order 3>
gap> g1 := RcwaMapping((1,2),[1..2]);
<rcwa permutation of Z with modulus 2, of order 2>
gap> G := Group(g1,g2);
<rcwa group over Z with 2 generators>
gap> phi := IsomorphismPermGroup(G);
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `RightCayleyDigraph' on 1 arguments at /Users/alexk/GITREPS/gap/lib/methsel2.g:249 called from
RightCayleyDigraph( S 
 ) at /Users/alexk/GITREPS/gap/pkg/semigroups-3.2.0/gap/semigroups/grpperm.gi:\
158 called from
<function "IsomorphismPermGroup for a semigroup">( <arguments> )
 called from read-eval loop at *stdin*:5
type 'quit;' to quit to outer loop
brk>
```

**Comment by Stefan-Kohl** [comment] 2019-10-22 17:00
Ah -- now things are clear! -- Instead of the 'IsomorphismPermGroup' method from RCWA, the 'IsomorphismPermGroup' method from the semigroups package is called. -- Even though the method for rcwa groups in RCWA is installed with rank offset SUM_FLAGS. -- And the method in 'semigroups' of course doesn't work for rcwa groups ... .

**Comment by Stefan-Kohl** [comment] 2019-10-23 12:27
@alex-konovalov How does it come that the method in the 'semigroups' package is called here? -- That method is installed for semigroups and WITHOUT rank offset ... . -- I thought it should always be the case that RankFilter(IsRcwaGroup) + SUM_FLAGS > RankFilter(IsSemigroup) ... (?)

**Comment by wilfwilson** [comment] 2019-10-23 13:21
This was fixed by @fingolfin in #20. So I recommend that you make a new release of RCWA, which will fix the problem, and then everything should be fine again.

**Comment by olexandr-konovalov** [comment] 2019-10-23 13:28
Indeed, the no-method-found is not there when the clone of this repository is tested - https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-devel/jobs/601605047. Test fail there because of a different reason, though.

**Comment by fingolfin** [comment] 2019-10-23 14:43
@alex-konovalov in those last tests, I see no package banner, which means I can't see what version of the package is loaded, which is annoying. Luckily the version can be seen in the 'TESTING WHETHER THE PACKAGE IS LOADABLE', so I am hoping it is the same in the others, but it would be really helpful if the package banner was shown.

Anyway, I managed to reproduce the problem locally, i.e. run `LoadAllPackages()` with a standard set of packages plus the dev version of RCWA, then run the RCWA tests.

This is expected by the tests:
```
gap> F := FreeProduct(Group((1,2)(3,4),(1,3)(2,4)),Group((1,2,3)),
>                     SymmetricGroup(3));
<fp group on the generators [ f1, f2, f3, f4, f5 ]>
gap> phi := IsomorphismRcwaGroup(F);
[ f1, f2, f3, f4, f5 ] -> [ <rcwa permutation of Z with modulus 12>, 
  <rcwa permutation of Z with modulus 24>, 
  <rcwa permutation of Z with modulus 12>, 
  <rcwa permutation of Z with modulus 72>, 
  <rcwa permutation of Z with modulus 36> ]
```
But what happens is that we get this:
```
gap> F := FreeProduct(Group((1,2)(3,4),(1,3)(2,4)),Group((1,2,3)),
>                     SymmetricGroup(3));
<fp group on the generators [ f1, f2, f3, f4, f5 ]>
gap> phi := IsomorphismRcwaGroup(F);
[ f1, f2, f3, f4, f5 ] -> [ ( 1(3), 3(12) ) ( 2(3), 9(12) ) ( 0(12), 6(12) ),
  ( 1(3), 0(24) ) ( 2(3), 12(24) ) ( 3(6), 6(12) ),
  <rcwa permutation of Z with modulus 12>,
  ( 0(3), 2(24) ) ( 1(3), 14(24) ) ( 8(12), 17(18) ) ( 5(18), 11(18) ),
  <rcwa permutation of Z with modulus 36> ]
```
What happens is that when all packages are loaded, for some reason, some of the rcwa permutations in the image "know" that they are in the filter `IsTame`, at least by the time we call `ViewObj` on the homomorphism, and hence they are printed in cycle notation. I do not yet know why this, though.

**Comment by olexandr-konovalov** [comment] 2019-10-23 14:47
@fingolfin just above "TESTING WHETHER THE PACKAGE IS LOADABLE" you should see
```
REPO_URL : https://github.com/gap-packages/rcwa.git
PKG_NAME : rcwa
Cloning into 'rcwa'...
commit 98aa50ffa7a85e3dff787c59ff69570114c88c27
Author: Max Horn <max@quendi.de>
Date:   Tue Sep 17 21:58:09 2019 +0200
    Add HasGeneratorsOfGroup filter to some methods
    
    ... which were using GeneratorsOfGroup. This fixes cases were no generators
    are set of a group in the filter IsRcwaGroup; e.g. for RCWA(Integers).
```
which is the ultimate source of information. Version number in the repository is less reliable.

**Comment by fingolfin** [comment] 2019-10-23 14:54
That only tells me what was *cloned*, but not what GAP *loads*. In the past I had trouble because GAP was actually loading a bad version of the RCWA package (not the dev version). This luckily doesn't seem to be the case here, but seeing explicitly which version of the package is loaded would be nice (or alternatively we must make sure that only the right version of the package is loaded -- as you know, I am working on a PR for that, too).

**Closed as completed** 2022-07-31 18:59 UTC
